# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-29 21:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('firstname', models.CharField(default='anonymous', max_length=30)),
                ('lastname', models.CharField(default='anonymous', max_length=30)),
                ('display_pic', models.FileField(default='anon.png', upload_to=b'')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='federal.Account')),
            ],
        ),
        migrations.CreateModel(
            name='CommentFavoriter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='federal.Account')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='federal.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('feed', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Lga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lga', models.CharField(max_length=100)),
                ('lga_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=b'')),
                ('audio', models.FileField(upload_to=b'')),
                ('video', models.FileField(upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('namespace', models.IntegerField()),
                ('state', models.IntegerField()),
                ('zone', models.IntegerField()),
                ('lga', models.IntegerField()),
                ('display_pic', models.FileField(default='anon.png', upload_to=b'')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='federal.Account')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='federal.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='ReplyFavoriter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='federal.Account')),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='federal.Reply')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=50)),
                ('state_code', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread', models.TextField()),
                ('namespace', models.IntegerField()),
                ('state', models.IntegerField()),
                ('zone', models.IntegerField()),
                ('lga', models.IntegerField()),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='federal.Account')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='ThreadFavoriter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='federal.Account')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='federal.Thread')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=100)),
                ('zone_code', models.IntegerField()),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='federal.State')),
            ],
        ),
        migrations.AddField(
            model_name='media',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='federal.Thread'),
        ),
        migrations.AddField(
            model_name='lga',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='federal.State'),
        ),
        migrations.AddField(
            model_name='lga',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='federal.Zone'),
        ),
        migrations.AddField(
            model_name='comment',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='federal.Thread'),
        ),
        migrations.AddField(
            model_name='account',
            name='lga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='federal.Lga'),
        ),
        migrations.AddField(
            model_name='account',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='federal.Position'),
        ),
        migrations.AddField(
            model_name='account',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='federal.State'),
        ),
        migrations.AddField(
            model_name='account',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='federal.Zone'),
        ),
    ]
