# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-02 13:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lga',
            options={'ordering': ['lga']},
        ),
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='zone',
            options={'ordering': ['state']},
        ),
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='reply',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
